### ISSUE TITLE
Invoke a Class System

### ISSUE THREAD

**Issue by dgoodwin01** [v-sec0/joeconomy#19]
Hear me out... we all start from rags to riches. There's certain milestones in-between which would add more of a "grind" mechanic to the game. Instead of being poor, you could be rich. Or vice versa, you could be rich but become poor.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented wealth levels (poor, middle-class, rich) and a grinding mechanic to the joeconomy project. Updated the user data structure, API response, and user interface to reflect these changes.

You can review changes in this commit: https://github.com/lkilu6456546/v-sec0-joeconomy-19/commit/ac82a4284dc6a01ebb56eb0ca4963280106cf415.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by v-sec0** [comment]
Class system will be inherit and understood.
